### ISSUE TITLE
Split long CSV imports into multiple smaller queries

### ISSUE THREAD

**Issue by TristanWiley** [JacobLinCool/d1-manager#45]
To avoid `statement too long`, we should split a SQL import into multiple small queries.

**Comment by JacobLinCool** [comment]
I think you are right, but I don't know where to get the size limit for D1 sql statements. I'm not sure if splitting each line into a statement is a good idea.

**Comment by TristanWiley** [comment]
Should be this https://developers.cloudflare.com/d1/platform/limits/

> Maximum SQL statement length: 100,000 bytes (100 KB)
