### ISSUE TITLE
Could you please give more detail about deployment?

### ISSUE THREAD

**Issue by banditsmile** [JacobLinCool/d1-manager#48]
Could you please give more detail about deployment,because I get 404 not found after I deploy this project to cloudflare pages.

project address:https://d.matlab.run/db/default

configuration about this project:
![image](https://github.com/JacobLinCool/d1-manager/assets/2239356/05de85f2-9c0e-4331-af27-a0225155c7b6)

**Comment by JacobLinCool** [comment]
Hi, it seems not the 404 page returned by d1-manager. D1 Manager 404 page: https://d1-manager.pages.dev/somewhere

Maybe you can checkout the custom domain tab and make sure that no other service uses the same DNS record:
<img width="930" alt="截圖 2024-03-19 下午5 19 08" src="https://github.com/JacobLinCool/d1-manager/assets/28478594/9b6dbd00-9a6b-4412-89d8-6496dc7d6aca">
